// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlmKQtCUsxrlGoTMZ3bSBjcxOIrYfdq48',
    appId: '1:219495156557:web:f228763ac2753416108504',
    messagingSenderId: '219495156557',
    projectId: 'smartlist-a6a8a',
    authDomain: 'smartlist-a6a8a.firebaseapp.com',
    storageBucket: 'smartlist-a6a8a.firebasestorage.app',
    measurementId: 'G-Y7SRHNZD2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt8hJg2izKxun3TtU15m8E7cuoQaXRir8',
    appId: '1:219495156557:android:fcb45bc76f3cf291108504',
    messagingSenderId: '219495156557',
    projectId: 'smartlist-a6a8a',
    storageBucket: 'smartlist-a6a8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0bkE23UMxzFKTFf1dLpMa5xnmeB6AgJs',
    appId: '1:219495156557:ios:099b25574ef2dcbc108504',
    messagingSenderId: '219495156557',
    projectId: 'smartlist-a6a8a',
    storageBucket: 'smartlist-a6a8a.firebasestorage.app',
    iosBundleId: 'com.example.feiranexus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0bkE23UMxzFKTFf1dLpMa5xnmeB6AgJs',
    appId: '1:219495156557:ios:099b25574ef2dcbc108504',
    messagingSenderId: '219495156557',
    projectId: 'smartlist-a6a8a',
    storageBucket: 'smartlist-a6a8a.firebasestorage.app',
    iosBundleId: 'com.example.feiranexus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlmKQtCUsxrlGoTMZ3bSBjcxOIrYfdq48',
    appId: '1:219495156557:web:b4f91d70fd37a7ee108504',
    messagingSenderId: '219495156557',
    projectId: 'smartlist-a6a8a',
    authDomain: 'smartlist-a6a8a.firebaseapp.com',
    storageBucket: 'smartlist-a6a8a.firebasestorage.app',
    measurementId: 'G-45XHHY09PD',
  );
}